export const GET_ALL_READER = 'GET_ALL_READER';
export const GET_ALL_READER_SAGA = 'GET_ALL_READER_SAGA';

export const CREATE_READER_SAGA = 'CREATE_READER_SAGA';

export const DELETE_READER_SAGA = 'DELETE_READER_SAGA';

export const UPDATE_READER_SAGA = 'UPDATE_READER_SAGA';

export const GET_READER = 'GET_READER';
export const GET_READER_SAGA = 'GET_READER_SAGA';